services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6.1
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
  postgres:
    image: postgres:18.3
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - ./docker/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
